[package]
name = "proxy-wasm-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.2.0"
log = "0.4"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
